services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./:/app:cached
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: "5432"
    command: air
    ports:
      - "8000:8000"
    depends_on:
      - db
