FROM golang:1.24-bookworm

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/air-verse/air@v1.62.0
RUN go install github.com/go-delve/delve/cmd/dlv@v1.24.2

ENV PATH="/root/go/bin:${PATH}"

COPY . .

CMD ["air"]
